In [1]:
import numpy as np
import pandas as pd

# 1. 时间类型数据概述

（1）时间类型数据的处理是数据分析中常见的操作。Python提供了很多时间处理的方式，如time、datetime、timeit等标准库，以及dateutil、Arrow、Maya等第三方库。  
（2）pandas提供了**Timestamp和Timedelta**两个时间类型数据相关的类、数据对象，以及很多时间类型数据处理相关的**函数和.dt接口**。此外，pandas还提供了period类，以及DatetimeIndex、PeriodtimeIndex、TimedetlaIndex等用于表示索引的几个类。<br> 
（3）一些相关概念：  
+ **日期（date）**：即年（year）、月（month）、日（day）的组合。如：2022年1月1日、**2022-01-01**、2022/1/1、20220101。  
+ **时间（time）**：即时（hour）、分（minute）、秒（second）以及纳秒（nanosecond）的组合。如：5:15:50，5:15:50.285714285。$1s=10^3ms=10^6μs=10^9ns=10^12ps$。  
+ **日期时间（datetime）**：即年-月-日 时:分:秒.纳秒的组合。如：2022-01-01 17:08:34.285714285。pandas中，这种日期时间类型数据的类型一般是**datetime64[ns]**，精确到纳秒，注意，在写的时候必须写64。  
+ **时间戳（Timestamp）**：时间轴上的一个时刻（点）。其起始原点一般指格林威治时间**1970-01-01 00:00:00:（北京时间1970-01-01 08:00:00:）**。因此，时间戳一般也理解为起始原点到某个时刻的**总秒数**。  
+ **时段（Period）**：表示一段时间，如1年、3年、1个月、10天、30秒等。pandas中，时段长短一般由**freq**参数确定，freq='Y'、freq='3Y'、freq='M'、freq='10D'、freq='M'、freq='30S'等。  
+ **时间间隔（Timedetla）**：表示两个时间之间的间隔，一般以天以及时、分、秒、毫秒等为计量标准。如：pd.Timestamp('2200-02-02 10:00:00.123456789') - pd.Timestamp('2000-01-01 00:00:00') = Timedelta('73081 days 10:00:00.123456789')。
+ 时段和时间间隔不同，时段就是一段时间，是一段时间的长度，没有特定的起始时间或结束时间，**更多是用来表示一种频率**；时间间隔一般特指某个结束时间与某个起始时间的差。

+ 时间字符串**格式控制**符号详见：https://docs.python.org/3/library/datetime.html#strftime-and-strptime-behavior  
+ 时段频率（freq参数）控制符号详见：https://docs.python.org/3/library/datetime.html#strftime-and-strptime-behavior. 
+ 主要时段频率控制符号：Y（年）、M（月）、D（天）、H（小时）、T（分钟）、S（秒）、W（周）、Q（季度）  
+ unit参数用于指定时间戳的单位:'s'：秒,'ms'：毫秒,'us'：微秒,'ns'：纳秒（默认）

**格式控制符号**：用于将日期时间对象格式化为字符串（strftime）或将字符串解析为日期时间对象（strptime）。它定义了日期时间各个组成部分（年、月、日、时、分、秒等）在字符串中的表示方式。  
**时段频率（freq参数）控制符号**：用于在pandas中指定时间序列的频率，例如生成日期范围、进行重采样等。它定义了两个连续时间点之间的间隔，常用于pd.date_range()、pd.DatetimeIndex、resample、asfreq  
**format参数**是一个字符串，它由格式控制符号和其他的分隔符（如'-'、':'等）组成。常用于pd.to_datetime()、strftime、strptime等函数

Python datetime 格式控制符号代码
| 符号         | 含义                            | 示例输出                 | 说明         |
| ------------ | ------------------------------- | ------------------------ | ------------ |
| **日期相关** |                                 |                          |              |
| `%Y`         | 4位数年份                       | 2025                     | 完整年份     |
| `%y`         | 2位数年份                       | 25                       | 年份后两位   |
| `%m`         | 月份（01-12）                   | 12                       | 补零月份     |
| `%d`         | 月内日期（01-31）               | 18                       | 补零日期     |
| **时间相关** |                                 |                          |              |
| `%H`         | 24小时制小时（00-23）           | 14                       | 24小时制     |
| `%I`         | 12小时制小时（01-12）           | 02                       | 12小时制     |
| `%M`         | 分钟（00-59）                   | 30                       | 补零分钟     |
| `%S`         | 秒（00-59）                     | 45                       | 补零秒数     |
| `%f`         | 微秒（6位数）                   | 123456                   | 微秒         |
| `%p`         | AM/PM 标识                      | AM                       | AM或PM       |
| **时区相关** |                                 |                          |              |
| `%z`         | UTC偏移（±HHMM[SS]）            | +0800                    | 时区偏移     |
| `%Z`         | 时区名称                        | CST                      | 时区名       |
| **周相关**   |                                 |                          |              |
| `%a`         | 星期缩写                        | Thu                      | 三字母缩写   |
| `%A`         | 星期全称                        | Thursday                 | 完整名称     |
| `%w`         | 星期数字（0-6，0=周日）         | 4                        | 数字表示     |
| `%W`         | 年内周数（00-53，周一为第一天） | 51                       | ISO周数      |
| `%U`         | 年内周数（00-53，周日为第一天） | 51                       | 美国周数     |
| **其他格式** |                                 |                          |              |
| `%j`         | 年内第几天（001-366）           | 352                      | 年积日       |
| `%b`         | 月份缩写                        | Dec                      | 三字母缩写   |
| `%B`         | 月份全称                        | December                 | 完整名称     |
| `%c`         | 日期和时间完整表示              | Thu Dec 18 14:30:45 2025 | 本地格式     |
| `%x`         | 日期表示                        | 12/18/25                 | 本地日期格式 |
| `%X`         | 时间表示                        | 14:30:45                 | 本地时间格式 |
| `%%`         | 百分号字符                      | %                        | 转义字符     |

常用格式控制符号模板
| 格式字符串              | 示例输出                    | 说明       |
| ----------------------- | --------------------------- | ---------- |
| `%Y-%m-%d %H:%M:%S`     | 2025-12-18 14:30:45         | 标准格式   |
| `%Y/%m/%d %H:%M:%S`     | 2025/12/18 14:30:45         | 斜杠分隔   |
| `%Y年%m月%d日 %H时%M分` | 2025年12月18日 14时30分     | 中文格式   |
| `%Y%m%d_%H%M%S`         | 20251218_143045             | 文件名格式 |
| `%Y-%m-%dT%H:%M:%S.%f`  | 2025-12-18T14:30:45.123456  | ISO扩展    |
| `%A, %B %d, %Y`         | Thursday, December 18, 2025 | 可读格式   |
| `%I:%M %p`              | 02:30 PM                    | 12小时制   |
| `%Y-%m-%d`              | 2025-12-18                  | 仅日期     |
| `%H:%M:%S`              | 14:30:45                    | 仅时间     |

时段频率（freq参数）控制符号
| 别名            | 等价字符串 | 描述         | 示例               |
| --------------- | ---------- | ------------ | ------------------ |
| **日频率**      |            |              |                    |
| `D`             | 'D'        | 日历日       | 每日               |
| `B`             | 'B'        | 工作日       | 周一到周五         |
| `C`             | 'C'        | 自定义工作日 | 自定义日           |
| **周频率**      |            |              |                    |
| `W`             | 'W'        | 周           | 每周               |
| `W-MON`         | 'W-MON'    | 周一为起始   | 每周一             |
| `W-TUE`         | 'W-TUE'    | 周二为起始   | 每周二             |
| **月频率**      |            |              |                    |
| `M`/`ME`        | 'M'        | 月末         | 每月最后一天       |
| `MS`            | 'MS'       | 月初         | 每月第一天         |
| `BM`/`BME`      | 'BM'       | 月末工作日   | 每月最后一个工作日 |
| `BMS`           | 'BMS'      | 月初工作日   | 每月第一个工作日   |
| **季度频率**    |            |              |                    |
| `Q`/`QE`        | 'Q'        | 季末         | 每季最后一天       |
| `QS`            | 'QS'       | 季初         | 每季第一天         |
| `BQ`/`BQE`      | 'BQ'       | 季末工作日   | 每季最后一个工作日 |
| `BQS`           | 'BQS'      | 季初工作日   | 每季第一个工作日   |
| **年频率**      |            |              |                    |
| `A`/`Y`/`YE`    | 'A'        | 年末         | 每年最后一天       |
| `AS`/`YS`       | 'AS'       | 年初         | 每年第一天         |
| `BA`/`BY`/`BYE` | 'BA'       | 年末工作日   | 每年最后一个工作日 |
| `BAS`/`BYS`     | 'BAS'      | 年初工作日   | 每年第一个工作日   |
| **小时频率**    |            |              |                    |
| `H`             | 'H'        | 小时         | 每小时             |
| `h`             | 'h'        | 小时（新版） | 每小时             |
| **分钟频率**    |            |              |                    |
| `T`/`min`       | 'T'        | 分钟         | 每分钟             |
| **秒频率**      |            |              |                    |
| `S`             | 'S'        | 秒           | 每秒               |
| **毫秒频率**    |            |              |                    |
| `L`/`ms`        | 'L'        | 毫秒         | 每毫秒             |
| **微秒频率**    |            |              |                    |
| `U`/`us`        | 'U'        | 微秒         | 每微秒             |
| **纳秒频率**    |            |              |                    |
| `N`             | 'N'        | 纳秒         | 每纳秒             |

编程语言日期格式
| 语言/框架  | 格式字符串            | 示例输出            | 说明             |
| ---------- | --------------------- | ------------------- | ---------------- |
| Python     | `%Y-%m-%d %H:%M:%S`   | 2025-12-18 14:30:45 | datetime         |
| JavaScript | `YYYY-MM-DD HH:mm:ss` | 2025-12-18 14:30:45 | moment.js        |
| Java       | `yyyy-MM-dd HH:mm:ss` | 2025-12-18 14:30:45 | SimpleDateFormat |
| C#         | `yyyy-MM-dd HH:mm:ss` | 2025-12-18 14:30:45 | .NET             |
| PHP        | `Y-m-d H:i:s`         | 2025-12-18 14:30:45 | date()函数       |

unit参数控制符号
| 符号             | 全称 | 说明         | 示例                                 |
| ---------------- | ---- | ------------ | ------------------------------------ |
| **基本时间单位** |      |              |                                      |
| `'ns'`           | 纳秒 | 纳秒（默认） | `pd.to_datetime(1, unit='ns')`       |
| `'us'`           | 微秒 | 微秒         | `pd.to_datetime(1000, unit='us')`    |
| `'ms'`           | 毫秒 | 毫秒         | `pd.to_datetime(1000000, unit='ms')` |
| `'s'`            | 秒   | 秒           | `pd.to_datetime(1, unit='s')`        |
| **天/周单位**    |      |              |                                      |
| `'D'`            | 天   | 天           | `pd.to_datetime(1, unit='D')`        |
| `'W'`            | 周   | 周           | `pd.to_datetime(1, unit='W')`        |
| **日期单位**     |      |              |                                      |
| `'Y'`            | 年   | 年           | 较少使用                             |
| `'M'`            | 月   | 月           | 较少使用                             |
| **组合单位**     |      |              |                                      |
| `'h'`            | 小时 | 小时         | 在 `Timedelta`中使用                 |
| `'m'`            | 分钟 | 分钟         | 在 `Timedelta`中使用                 |

# 2. Timestamp

## 2.1 Timestamp的创建

可以通过pd.Timestamp()函数将**一个时间格式的字符串**转换成Timestamp类型，或通过其他属性获取。注意：不适用于Series对象。此外，pd.to_datetime()函数将一个时间格式的字符串转换成Timestamp类型或一个Series对象的时间格式字符串转换成日期时间类型。

In [ ]:
# （1）获取电脑系统当前时间戳

In [ ]:
# （2）从字符串创建,2025-01-01,2025/01/01,2025/01/01 1:2:3.123456789
# 不支持pd.Timestamp('2022年01月01日')

In [ ]:
# （3）从时间戳（整数）创建
  # Unix时间戳是从1970年1月1日00:00:00 UTC开始到现在的秒数

【思考】为什么要将时间格式的字符串转换成Timestamp类型。

1.统一时间格式：字符串表示的时间格式多样，如'2023-12-25'、'2023/12/25'、'25-12-2023'等，转换为Timestamp后，pandas会将其统一为内部表示（纳秒级别的时间戳），便于后续处理。   

2.时间运算：Timestamp对象支持与Timedelta进行加减运算，可以方便地进行时间偏移、计算时间间隔等。  

3.时间属性访问：转换为Timestamp后，可以轻松获取年、月、日、小时、星期等属性，以及判断是否为月初、月末、季度末等。
时间序列索引：在pandas中，将时间转换为Timestamp后，可以作为时间序列索引（DatetimeIndex），进而进行重采样、滑动窗口等高级时间序列操作。

In [ ]:
s = '2025-12-18 10:11:12'

In [ ]:
# 是月中的第几天，是一周的第几天

In [ ]:
# 运算

## 2.2 Timestamp的运算

+ 两个Timestamp之间可以进行-（不能+、\*、/）等算术运算，表示两个Timestamp的间隔，**两个Timestamp减法运算的结果是Timedetla类型**。<br>
+ 两个Timestamp之间可以进行逻辑运算或条件运算。
+ Timestamp和Timedelta之间可以进行 + 运算。

In [ ]:
ts1 = pd.Timestamp(year=2025, month=1, day=1, hour=1, minute=1, second=1)
ts2 = pd.Timestamp.now()

In [ ]:
# 两个Timestamp算术运算

In [ ]:
# 两个Timestamp条件运算或逻辑运算
# 逻辑运算and ts1为真，所以返回ts2, or ts1为真，所以返回ts1

【思考】下述时间差的总秒数？

In [ ]:
time = (pd.Timestamp.now() - pd.Timestamp('1970-01-01 08:00:00'))
time

In [ ]:
# 总秒数差

## 2.3 Timestamp的属性和方法

| 序号 | 函数/方法                              | 作用                                                         | 其他说明                                             |
| ---- | :-------------------------------------- | :------------------------------------------------------------ | :---------------------------------------------------- |
| 1    | ts.year                                | 时间戳ts的年份。                                             |                                                      |
| 2    | ts.month                               | 时间戳ts的月份。                                             |                                                      |
| 3    | ts.day                                 | 时间戳ts的天数,（月中的第几天）。                                             |                                                      |
| 4    | ts.hour                                | 时间戳ts的小时。                                             |                                                      |
| 5    | ts.minute                              | 时间戳ts的分钟。                                             |                                                      |
| 6    | ts.second                              | 时间戳ts的秒。                                               |                                                      |
| 7    | ts.quarter                             | 时间戳ts的季度。                                             |                                                      |
| 8    | ts.week、ts.weekofyear                 | 时间戳ts在一年中是第几周。                                   |                                                      |
| 9    | ts.day_of_week、ts.dayofweek           | 时间戳ts的天数是一周中的第几天。                             | 0表示星期1；6表示星期天。                            |
| 10   | ts.day_of_year、ts.dayofyear           | 时间戳ts的天数是一年中的第几天。                             | 1表示1月1日。                                        |
| 11   | ts.days_in_month、ts.daysinmonth       | 时间戳ts的月份一共有多少天。                                 | 如二月有28或29天。                                   |
| 12   | ts.is_month_start、ts.is_month_end     | 时间戳ts是否是所在月的第一天、最后一天。                     |                                                      |
| 13   | ts.is_quarter_start、ts.is_quarter_end | 时间戳ts是否是所在季度的第一天、最后一天。                   |                                                      |
| 14   | ts.is_year_start、ts.is_year_end       | 时间戳ts是否是所在年份的第一天、最后一天。                   |                                                      |
| 15   | ts.is_leap_year                        | 时间戳ts的年份是否是闰年。                                   |                                                      |
| 16   | ts.day_name()                          | 时间戳ts的天数是一周中的星期几（英文名称）。如ts.day_name()-->'Sunday'。 |                                                      |
| 17   | ts.month_name()                        | 时间戳ts的月份是一年中的第几月（英文名称）。如ts.month_name()-->'May'。 |                                                      |
| 18   | ts.replace()                           | 将时间戳ts的部分数据替换成新的数据，如ts.replace(year=2023,day=20) | 产生新的值。                                         |
| 19   | ts.timestamp()                         | 时间戳ts距离起始时间（北京1970-01-01 08:00:00）的总秒数。    |                                                      |
| 20   | ts.to_pydatetime()                     | 将时间戳ts转换成datetime.datetime类型。                      |                                                      |
| 21   | ts.date()                              | 将时间戳ts转换成datetime.date类型。                          |                                                      |
| 22   | ts.to_datetime64()、ts.to_numpy()      | 将时间戳ts转换成numpy.datetime64类型。                       |                                                      |
| 23   | ts.strftime()                          | 将时间戳ts以给定字符串的格式进行输出，如ts.strftime('%Y%m%d %H:%M:%S') | 只能写%，不支持format()方法。<br>时间字符串格式控制符号详见：https://docs.python.org/3/library/datetime.html#strftime-and-strptime-behavior.                       |
| 24   | ts.strptime()                          | 将字符串类型转换（解析）成日期时间类型。                     | **此方法已经弃用**，可使用**pd.to_datetime()**实现。 |

In [ ]:
ts = pd.Timestamp.now()
ts

In [ ]:
# 获取年，月，日，时，分，秒，季度

In [ ]:
# 一年中是第几周，一周中的第几天，一年中的第几天，月份一共有多少天

In [ ]:
# 是所在月的第一天、最后一天，是所在季度的第一天、最后一天，是所在年份的第一天、最后一天

In [ ]:
# 年份是否是闰年

In [ ]:
# 天数是一周中的星期几，月份是一年中的第几月

In [ ]:
# 时间戳ts的部分数据替换成新的数据

In [ ]:
# 时间戳ts距离起始时间（北京1970-01-01 08:00:00）的总秒数

In [ ]:
# 以给定字符串的格式进行输出,以年月日时分秒上午或者下午进行输出

## 2.4 .dt接口（accessor）

**Timestamp的属性和方法只能适用于单个Timestamp对象**，不适用于Series对象和DataFrame对象。因此，pandas提供了.dt接口，该接口适用于Series对象。不过，该接口提供的属性和方法并不完全覆盖Timestamp的属性和方法，例如'DatetimeProperties' object has no attribute 'timestamp'。二者的关系类似于原生python中的字符串函数和pandas中str类下面的字符串函数。

In [ ]:
df = pd.DataFrame([[pd.Timestamp.now()],[pd.Timestamp('2025-01-01')],[pd.Timestamp('1970-01-01')]],columns=['date'])
df

In [ ]:
# 数据类型

In [ ]:
# 新增一列数据为当前date列的年份

In [ ]:
# 新增两列数据，一列名为dayName，值为天数是一周中的星期几,一列名为month，值为月份，

# 3. Timedetla

## 3.1 Timedetla的创建

+ 可以通过pd.Timedelta()函数进行创建，也可以通过两个Timestamp相减运算创建。
+ Timedelta的默认单位是毫秒。

In [ ]:
# 创建一个时间间隔为10天10时10分10秒,10 days 10:10:10, 10 days 10 hours 10 minutes 10 seconds

In [ ]:
# 创建一个10毫秒时间间隔，10分钟时间间隔，10天时间间隔

In [ ]:
# 当年时间与原始时间（北京时间）的间隔，通过两个Timestamp相减运算

## 3.2 Timedetla的运算

+ 两个Timedetla之间可以进行+、-、/（不能*）等算术运算，以及逻辑运算和条件运算。
+ Timestamp和Timedetla之间可以进行+、-运算。

In [ ]:
td1 = pd.Timedelta('10 days 10:10:10')
td2 = pd.Timedelta('20 days 20:30:30')

In [ ]:
# + -算术运算

In [ ]:
# 条件运算

In [ ]:
# Timestamp和Timedetla之间可以进行+、-运算

## 3.3 Timedetla的属性和方法

| 属性                | 描述                   |
| ------------------- | ---------------------- |
| **`.days`**         | 天数部分（可以是负数） |
| **`.seconds`**      | 秒数部分（0-86399）    |
| **`.microseconds`** | 微秒部分（0-999999）   |
| **`.nanoseconds`**  | 纳秒部分（0-999）      |
| **`.value`**        | 内部表示（纳秒）       |
| **`.resolution`**   | 最小分辨率             |
| **`.components`**   | 所有组成部分           |

| 方法                    | 描述                                |
| ----------------------- | ----------------------------------- |
| **`.total_seconds()`**  | 总秒数（包含小数）                  |
| **`.to_pytimedelta()`** | 转换为Python标准库timedelta         |
| **`.to_timedelta64()`** | 转换为numpy.timedelta64             |
| **`.to_numpy()`**       | 转换为numpy数组（同to_timedelta64） |
| **`.isoformat()`**      | ISO 8601格式字符串                  |
| **`.round()`**          | 四舍五入到指定频率                  |

In [ ]:
td1 = pd.Timestamp.now() - pd.Timestamp('1970-01-01 08:00:00')
td2 = pd.Timedelta('10 days 10:10:10')
td1, td2

In [ ]:
# 时间间隔所有组成部分

In [ ]:
# 时间间隔的天数

In [ ]:
# 时间间隔的总秒数

# 4. 常用时间处理函数

| 序号 | 函数/方法        | 作用                                                         | 示例                                                         | 主要参数                                                     | 其他说明                                                   |
| :---- | :---------------- | :------------------------------------------------------------ | :------------------------------------------------------------ | :------------------------------------------------------------ | :---------------------------------------------------------- |
| 1    | pd.date_range()  | 返回一个指定间隔的日期时间索引（DatetimeIndex）。            | pd.date_range('2022-1-1','2022-6-30',10)<br />pd.date_range('2022-1-1','2022-6-30',freq='10D') | start：字符串。开始时间。<br />end：字符串。结束时间。<br />periods：int类型。产生时间的数量。<br />freq：间隔频率。默认‘D’。Y、M、D、H、T、S、W、Q依次表示年、月、日、时、分、秒、周、季度。 | 在start、end、period和freq这四个参数中，只有三个必须指定，最常见的组合：start + end + freq或 start + periods + freq。 |
| 2    | pd.to_datetime() | 将其他类型数据转换成datetime64[ns]类型。返回一个Timestamp对象。 | pd.to_datetime(10)<br />pd.to_datetime('2022-04-01')         | arg：被转换的对象。int, float, str, datetime, list, tuple, 1-d array, Series, DataFrame/dict-like<br />errors：'raise'，报错；'ignore'，不报错，保持原始值；'coerce'，不报错，设置为NaT。<br />unit：arg的单位，默认ns，其他如d（天），Y（年）等。<br />format=None,格式字符串。 |                                                            |

## 4.1 pd.date_range()
生成固定频率日期时间序列的核心函数

In [ ]:
# (1)start、end、freq
# 生成2025年12月的所有日期

In [ ]:
# （2）start、period、freq
# 从2025-12-01开始，生成10个工作日

In [ ]:
# （3）start、end、period
# 生成2025年12月里面的10个日期

In [ ]:
# （4）end、period、freq
# 以2025-12-31结束，向前生成5个季末日期

## 4.2 pd.to_datetime()
将各种格式的输入转换为 datetime 对象的核心函数

In [ ]:
# 转换单个字符串

In [ ]:
# 转换多个字符串, ['2025-12-18', '2025-12-19', '2025-12-20']

In [ ]:
# 异常处理，errors='coerce'或'ignore' , ['2025-04-01','2025/12/19','2025年1月1日']

In [ ]:
# unit转换

In [ ]:
# format转换,2025-04-01, 2025/01/04, 25年04月01日

In [ ]:
# format转换, ['18-12-2025 14:30','19-12-2025 15:45','20-12-2025 09:15']

# 5. 练习与答案

【练习】读取日期时间数据.xlsx，查看数据类型，将所有数据转换成datetime64类型。

In [2]:
# 读取数据命名df，预览前2行
df = pd.read_excel(r'数据源/日期时间数据.xlsx')
df.head(2)

          A      B
0  2022-1-1  44562
1  2022-1-2  44563

In [3]:
# 查看数据集基本信息
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       10 non-null     object
 1   B       10 non-null     int64
dtypes: int64(1), object(1)
memory usage: 292.0+ bytes

In [4]:
# 新增一列数据，为A列数据转换为日期时间类型数据
df['A_'] = pd.to_datetime(df['A'])
df

           A      B         A_
0   2022-1-1  44562 2022-01-01
1   2022-1-2  44563 2022-01-02
2   2022-1-3  44564 2022-01-03
3   2022-1-4  44565 2022-01-04
4   2022-1-5  44566 2022-01-05
5   2022-1-6  44567 2022-01-06
6   2022-1-7  44568 2022-01-07
7   2022-1-8  44569 2022-01-08
8   2022-1-9  44570 2022-01-09
9  2022-1-10  44571 2022-01-10

In [5]:
# B列数据转换为正确的日期格式
pd.Timestamp('1899-12-30') + pd.Timedelta(44562,unit= 'D')

Timestamp('2022-01-01 00:00:00')

In [6]:
# 将全部B列数据转换为正确的日期格式
def int_to_datetime(num):
    return pd.Timestamp('1899-12-30') + pd.Timedelta(num,unit= 'D')
df['B_'] = df['B']. map(int_to_datetime)
df

           A      B         A_         B_
0   2022-1-1  44562 2022-01-01 2022-01-01
1   2022-1-2  44563 2022-01-02 2022-01-02
2   2022-1-3  44564 2022-01-03 2022-01-03
3   2022-1-4  44565 2022-01-04 2022-01-04
4   2022-1-5  44566 2022-01-05 2022-01-05
5   2022-1-6  44567 2022-01-06 2022-01-06
6   2022-1-7  44568 2022-01-07 2022-01-07
7   2022-1-8  44569 2022-01-08 2022-01-08
8   2022-1-9  44570 2022-01-09 2022-01-09
9  2022-1-10  44571 2022-01-10 2022-01-10

In [7]:
# 查看数据类型
df.dtypes

A             object
B              int64
A_    datetime64[ns]
B_    datetime64[ns]
dtype: object

# 6. 总结

|                | Timestamp                                                    | Timedetla                                                    |
| :-------------- | :------------------------------------------------------------ | :----------------------------------------------------------- |
| 创建           | pd.Timestamp()创建（使用单个字符串）<br />pd.Timestamp.now()获取<br />pd.to_datetime()转换（单个字符串或Series） | pd.Timedelta()创建<br />两个Timestamp相减。                  |
| 运算           | 可以进行：-运算；关系运算；逻辑运算。<br />不可以进行：+、*、/运算 | 可以进行：+、-、/运算；关系运算；逻辑运算。<br />不可以进行：*运算 |
| 常用属性或方法 | ts.year、ts.month、ts.day、ts.hour、ts.minute、ts.second、ts.quarter、ts.weekofyear、ts.dayofweek（星期几，数字，从0开始）、ts.dayofyear、ts.daysinmonth、ts.is_month_start、ts.is_month_end、ts.is_quarter_start、ts.is_quarter_end、ts.is_year_start、ts.is_year_end、ts.is_leap_year、ts.day_name()（星期几，英文名称）、ts.month_name()、ts.timestamp() | td.components<br />td.days<br />td.total_seconds()<br />td.delta<br />不支持其他时间差属性：如年、月等。 |
| .dt接口        | Timestamp上述常用属性适用于一个字符串，.dt接口适用于Series。 |                                                              |

 + Excel中，用整数表示年份时，整数代表从“1899-12-30”开始到年份的天数days。
 + pd.to_datetime()可以将单个字符串或一组字符串列表或Series转换成datetime类型。