In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
plt.rcParams['font.family'] = 'SimHei'
%matplotlib inline

# 1. str类概述

（1）pandas中提供了处理字符串操作专门的类（str）,但是这个类**只对Series对象和Index对象有效，对DataFrame对象无效。**<br>  
（2）str类中提供了50多种字符串处理方法。总的来说，这些方法和python原生语法中字符串处理方法类似。  只能作用于一维数据  
（3）注意：如果要同时使用str类下面的多个方法实现链式编程写法，则**每个方法前面均须要完整的写上str.方法名()**。如：series.str.方法1().str.方法2().str.方法3()...。  
（4）str类中的split()、replace()、contains()、count()均支持多个字符的“或”操作，但是需要**转义符（\）和或运算符（|）配合使用**，不能只写|。  
（5）类似的效果可以通过Series.map()函数实现。

# 2. 字符串的索引和切片

In [2]:
s = pd.Series([' lower ', 'CAPI TALS', 'this is a sentence ', 'SwApCaSe',np.nan])
s

0                 lower
1              CAPI TALS
2    this is a sentence
3               SwApCaSe
4                    NaN
dtype: object

In [3]:
# 取出索引为0
s.str[0]

0
1      C
2      t
3      S
4    NaN
dtype: object

In [4]:
# 切出前3个字符
s.str[:3]

0     lo
1    CAP
2    thi
3    SwA
4    NaN
dtype: object

In [5]:
# 反向输出所有字符
s.str[::-1]

0                 rewol
1              SLAT IPAC
2     ecnetnes a si siht
3               eSaCpAwS
4                    NaN
dtype: object

# 3. 字符串的长度

In [6]:
s = pd.Series([' lower ', 'CAPI TALS', 'this is a sentence ', 'SwApCaSe',np.nan])
# 字符长度
s.str.len()

0     7.0
1     9.0
2    19.0
3     8.0
4     NaN
dtype: float64

# 4. 字符串大小写转换

| 序号 | 方法             | 作用                                    | 示例                                                  | 主要参数 | 其他说明 |
| ---- | :---------------- | :--------------------------------------- | :----------------------------------------------------- | :-------- | :-------- |
| 1    | str.lower()      | 将字符串的所有字符变成小写。            | s = pd.Series(['AB', 'cd'])<br/>s.str.lower()         |          |          |
| 2    | str.upper()      | 将字符串的所有字符变成大写。            | s = pd.Series(['AB', 'cd'])<br/>s.str.upper()         |          |          |
| 3    | str.capitalize() | 将整个字符串的第1个字母变成大写。       | s = pd.Series(['AB AB', 'cd'])<br/>s.str.capitalize() |          |          |
| 4    | str.title()      | 将字符串的每个单词的第1个字母变成大写。 | s = pd.Series(['AB AB', 'cd'])<br/>s.str.title()      |          |          |
| 5    | str.swapcase()   | 字符串的大小写互换。                    | s = pd.Series(['AB AB', 'cd'])<br/>s.str.swapcase()   |          |          |

In [7]:
s = pd.Series(['lower', 'CAPITALS', 'this is a sentence', 'SwApCaSe'])

In [8]:
# 将字符串的所有字符变成小写
s.str.lower()

0                 lower
1              capitals
2    this is a sentence
3              swapcase
dtype: object

In [9]:
# 将字符串的所有字符变成大写
s.str.upper()

0                 LOWER
1              CAPITALS
2    THIS IS A SENTENCE
3              SWAPCASE
dtype: object

In [10]:
# 将整个字符串的第1个字母变成大写
s.str.capitalize()

0                 Lower
1              Capitals
2    This is a sentence
3              Swapcase
dtype: object

In [11]:
# 将字符串的每个单词的第1个字母变成大写
s.str.title()

0                 Lower
1              Capitals
2    This Is A Sentence
3              Swapcase
dtype: object

In [12]:
# 字符串的大小写互换
s.str.swapcase()

0                 LOWER
1              capitals
2    THIS IS A SENTENCE
3              sWaPcAsE
dtype: object

# 5. 字符串两端字符的移除

| 序号 | 方法         | 作用                               | 示例                                                         | 主要参数 | 其他说明 |
| ---- | :------------ | :---------------------------------- | :------------------------------------------------------------ | :-------- | :-------- |
| 1    | str.strip()  | 移除字符串两端的字符，默认是空格。 | s = pd.Series([' AB', 'A B',' A B ',' AB '])<br/>s.str.strip() |          |          |
| 2    | str.lstrip() | 移除字符串左边的字符，默认是空格。 | s = pd.Series([' AB', 'A B',' A B ',' AB '])<br/>s.str.lstrip('A') |          |          |
| 3    | str.rstrip   | 移除字符串右边的字符，默认是空格。 | s = pd.Series([' AB', 'A B',' A B ',' AB '])<br/>s.str.rstrip('B') |          |          |

In [13]:
s = pd.Series([' lower ', 'CAPI TALS', 'this is a sentence ', 'SwApCaSe',np.nan])
s.str.len()

0     7.0
1     9.0
2    19.0
3     8.0
4     NaN
dtype: float64

In [14]:
# 移除字符串两端的字符
s.str.strip().str.len()

0     5.0
1     9.0
2    18.0
3     8.0
4     NaN
dtype: float64

# 6. 字符串的分割

| 序号 | 方法        | 作用                                                 | 示例                                                         | 主要参数                                                     | 其他说明                                                     |
| ---- | :----------- | :---------------------------------------------------- | :------------------------------------------------------------ | :------------------------------------------------------------ | :------------------------------------------------------------ |
| 1    | str.split() | 按照给定的符号**（默认是空格）**，将字符串进行分割。 | s.str.split('+')<br />s.str.split('\\+\|-\| ', expand=True) | pat：指定的分割符号（默认是空格。<br />n：分词的次数。None、0、-1表示分割整个字符串<br />expand：是否将分割后的字符串放在不同的列（扩展为一个DataFrame对象）。 | pat支持用**“\|”**符号连接多种不同的字符进行分割。但是，**必须在最前面加转义符**。 |

In [15]:
s = pd.Series(['1-2-3-4-5-6', 'A+B+C+D+E+F', 'a b c d e f'])
s

0    1-2-3-4-5-6
1    A+B+C+D+E+F
2    a b c d e f
dtype: object

In [16]:
# 按照空格分割
s.str.split( )

0         [1-2-3-4-5-6]
1         [A+B+C+D+E+F]
2    [a, b, c, d, e, f]
dtype: object

In [17]:
# 按照+分割
s.str.split('+')

0         [1-2-3-4-5-6]
1    [A, B, C, D, E, F]
2         [a b c d e f]
dtype: object

In [18]:
# 按照+分割2次  ,前两个
s.str.split('+',n = 2)

0      [1-2-3-4-5-6]
1    [A, B, C+D+E+F]
2      [a b c d e f]
dtype: object

In [19]:
# 按照-分割并将分割后的字符串放在不同的列    Dateframe
s.str.split('-',expand = True)

             0     1     2     3     4     5
0            1     2     3     4     5     6
1  A+B+C+D+E+F  None  None  None  None  None
2  a b c d e f  None  None  None  None  None

In [20]:
# 重要转义符：\ ，同时 regex: 'bool | None' = None，可以表示为正则表达式分割
# 按照+ - 空格分割并将分割后的字符串放在不同的列
s.str.split(r'\+|-| ',expand = True)

   0  1  2  3  4  5
0  1  2  3  4  5  6
1  A  B  C  D  E  F
2  a  b  c  d  e  f

# 7. 字符串的替换

str类下面的str.replace()方法与pandas中Series对象和DataFrame对象的replace()方法不同，前者是替换字符串里面的符号，而后者是替换字符串。前者类似于Excel表中的普通替换模式，后者类似于Excel表中的单元格匹配替换模式。

| 序号 | 方法          | 作用                             | 示例                          | 主要参数                                                     | 其他说明                                                     |
|:---- | :------------- | :-------------------------------- | :----------------------------- | :------------------------------------------------------------ | :------------------------------------------------------------ |
| 1    | str.replace() | 将字符串中的符号替换成其他符号。 | s.str.replace('\+\|-\| ','=') | pat：被替换的字符。<br />repl：替换后的新字符。<br />case：是否大小写敏感，默认区分。<br /> | pat支持用“\|”符号连接多种不同的字符进行分割。但是，**必须在最前面加转义符**。 |

In [21]:
df = pd.DataFrame(
    [['ABC', 'ABD', 'ABC'], ['ABE', 'FGH', 'ABD']], columns=['第一列', '第二列', '第三列'])
df

   第一列  第二列  第三列
0  ABC  ABD  ABC
1  ABE  FGH  ABD

In [22]:
# DataFrame对象的replace()方法，支持inplace参数
# 将'ABC'转换为'ABK'
df.replace('ABC','ABK')

   第一列  第二列  第三列
0  ABK  ABD  ABK
1  ABE  FGH  ABD

In [23]:
# 将'AB'转换为'12'

In [24]:
s = pd.Series(['1-2-3-4-5-6', 'A+B+C+D+E+F', 'a b c d e f'])
s

0    1-2-3-4-5-6
1    A+B+C+D+E+F
2    a b c d e f
dtype: object

In [25]:
# 将+替换为-
s.str.replace('+','-')

0    1-2-3-4-5-6
1    A-B-C-D-E-F
2    a b c d e f
dtype: object

In [26]:
# 将+ - 和空格都替换为=，其中regex: 'bool' = False，此时需要显示指定regex= True
s.str.replace('\+|-|','=',regex = True)

<>:2: SyntaxWarning: invalid escape sequence '\+'
<>:2: SyntaxWarning: invalid escape sequence '\+'
C:\Users\leng\AppData\Local\Temp\ipykernel_7096\2628081779.py:2: SyntaxWarning: invalid escape sequence '\+'
  s.str.replace('\+|-|','=',regex = True)

0         =1==2==3==4==5==6=
1         =A==B==C==D==E==F=
2    =a= =b= =c= =d= =e= =f=
dtype: object

In [27]:
# 第二种方式字符类[]

# 8. 字符串的匹配

| 序号 | 方法             | 作用                       | 示例                           | 主要参数                                      | 其他说明         |
| :---- | :---------------- | :-------------------------- | :------------------------------ | :--------------------------------------------- | :---------------- |
| 1    | str.contains()   | 判断是否包含某个字符串。   | s.str.contains('A',case=False) | pat：匹配字符串。<br />case：默认区分大小写。 |                  |
| 2    | str.startswith() | 判断是否以某个字符串开头。 | s.str.startswith('Bc')         | pat：匹配字符串。                             | 不支持case参数。 |
| 3    | str.endswith()   | 判断是否以某个字符串结尾。 | s.str.endswith('D')            | pat：匹配字符串。                             | 不支持case参数。 |

In [28]:
s = pd.Series(['ABC','abc','BcD','bcd'])

In [29]:
# 是否包含B或D，不区分大小写
s.str.contains('B|D', case=False)

0    True
1    True
2    True
3    True
dtype: bool

In [30]:
# 是否以Bc开头
s.str.startswith('Bc')

0    False
1    False
2     True
3    False
dtype: bool

In [31]:
# 是否以D结尾
s.str.endswith('D')

0    False
1    False
2     True
3    False
dtype: bool

# 9. 字符串的计数

| 序号 | 方法        | 作用                             | 示例             | 主要参数          | 其他说明         |
| ---- | :----------- | :-------------------------------- | :---------------- | :----------------- | :---------------- |
| 1    | str.count() | 统计字符串中包含某个字符的数量。 | s.str.count('A') | pat：匹配字符串。 | 不支持case参数。 |

In [32]:
s = pd.Series(['ABCAa','abc','BcD','bcd'])

In [33]:
# 包含A字符的数量
s.str.count('A')

0    2
1    0
2    0
3    0
dtype: int64

# l0.练习

In [34]:
data = {
    '姓名': ['孙强', '王小明', np.nan, '李华', '朱琳', '赵丽', np.nan, '张伟', '陈静', '吴刚'],
    '性别': ['男', '男', '男', 'f', '男', 'm', 'm', 'm', '男', '女'],
    '语文成绩': ['77', '74', np.nan, '95', '97', '75', '91', '75', '94', '67'],
    '数学成绩': ['74', '98', '82', '100', '75', '74', np.nan, '95', '81', '99'],
    '身份证号': [
        '110101-19970219-5320', 
        '863794026542351234', 
        '330102 880124 570802', 
        '931034131647525534', 
        np.nan, 
        '440301920503316932', 
        np.nan, 
        '965328710122691782', 
        '440301930315103420', 
        '440301-850925-643020'
    ]}
df = pd.DataFrame(data)
df

    姓名 性别 语文成绩 数学成绩                  身份证号
0   孙强  男   77   74  110101-19970219-5320
1  王小明  男   74   98    863794026542351234
2  NaN  男  NaN   82  330102 880124 570802
3   李华  f   95  100    931034131647525534
4   朱琳  男   97   75                   NaN
5   赵丽  m   75   74    440301920503316932
6  NaN  m   91  NaN                   NaN
7   张伟  m   75   95    965328710122691782
8   陈静  男   94   81    440301930315103420
9   吴刚  女   67   99  440301-850925-643020

（1）将姓名列缺失值填充为'未知'  
（2）统一性别格式，将f转换为女，m转换为男  
（3）将语文成绩和数据成绩转换为数值型数据，同时对于缺失部分填充为0  
（4）清洗身份证号  
（5）计算男、女语文数学平均成绩

In [43]:
# （1）将姓名列缺失值填充为'未知'
df['姓名'] = df['姓名'].fillna('未知')
df

    姓名 性别  语文成绩   数学成绩                  身份证号            身份证号_清洗后
0   孙强  男  77.0   74.0  110101-19970219-5320  110101199702195320
1  王小明  男  74.0   98.0    863794026542351234  863794026542351234
2   未知  男   0.0   82.0  330102 880124 570802  330102880124570802
3   李华  女  95.0  100.0    931034131647525534  931034131647525534
4   朱琳  男  97.0   75.0                   NaN                 NaN
5   赵丽  男  75.0   74.0    440301920503316932  440301920503316932
6   未知  男  91.0    0.0                   NaN                 NaN
7   张伟  男  75.0   95.0    965328710122691782  965328710122691782
8   陈静  男  94.0   81.0    440301930315103420  440301930315103420
9   吴刚  女  67.0   99.0  440301-850925-643020  440301850925643020

In [37]:
# （2）统一性别格式，将f转换为女，m转换为男
# 方法1
df['性别'].replace({'f':'女','m':'男'},inplace = True)
df

    姓名 性别 语文成绩 数学成绩                  身份证号
0   孙强  男   77   74  110101-19970219-5320
1  王小明  男   74   98    863794026542351234
2   未知  男  NaN   82  330102 880124 570802
3   李华  女   95  100    931034131647525534
4   朱琳  男   97   75                   NaN
5   赵丽  男   75   74    440301920503316932
6   未知  男   91  NaN                   NaN
7   张伟  男   75   95    965328710122691782
8   陈静  男   94   81    440301930315103420
9   吴刚  女   67   99  440301-850925-643020

In [38]:
# 方法2
df['性别'] = df['性别'].str.replace('m','男').str.replace('f','女')
df

    姓名 性别 语文成绩 数学成绩                  身份证号
0   孙强  男   77   74  110101-19970219-5320
1  王小明  男   74   98    863794026542351234
2   未知  男  NaN   82  330102 880124 570802
3   李华  女   95  100    931034131647525534
4   朱琳  男   97   75                   NaN
5   赵丽  男   75   74    440301920503316932
6   未知  男   91  NaN                   NaN
7   张伟  男   75   95    965328710122691782
8   陈静  男   94   81    440301930315103420
9   吴刚  女   67   99  440301-850925-643020

In [39]:
# 数据集基本信息
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   姓名      10 non-null     object
 1   性别      10 non-null     object
 2   语文成绩    9 non-null      object
 3   数学成绩    9 non-null      object
 4   身份证号    8 non-null      object
dtypes: object(5)
memory usage: 532.0+ bytes

In [40]:
# （3）将语文成绩和数据成绩转换为数值型数据，同时对于缺失部分填充为0
df['语文成绩'] = pd.to_numeric(df['语文成绩'],errors = 'coerce').fillna(0)
df['数学成绩'] = pd.to_numeric(df['数学成绩'],errors = 'coerce').fillna(0)
df

    姓名 性别  语文成绩   数学成绩                  身份证号
0   孙强  男  77.0   74.0  110101-19970219-5320
1  王小明  男  74.0   98.0    863794026542351234
2   未知  男   0.0   82.0  330102 880124 570802
3   李华  女  95.0  100.0    931034131647525534
4   朱琳  男  97.0   75.0                   NaN
5   赵丽  男  75.0   74.0    440301920503316932
6   未知  男  91.0    0.0                   NaN
7   张伟  男  75.0   95.0    965328710122691782
8   陈静  男  94.0   81.0    440301930315103420
9   吴刚  女  67.0   99.0  440301-850925-643020

In [41]:
# （4）清洗身份证号
df['身份证号_清洗后'] = df['身份证号'].str.replace(r'[^0-9]','',regex = True)
df

    姓名 性别  语文成绩   数学成绩                  身份证号            身份证号_清洗后
0   孙强  男  77.0   74.0  110101-19970219-5320  110101199702195320
1  王小明  男  74.0   98.0    863794026542351234  863794026542351234
2   未知  男   0.0   82.0  330102 880124 570802  330102880124570802
3   李华  女  95.0  100.0    931034131647525534  931034131647525534
4   朱琳  男  97.0   75.0                   NaN                 NaN
5   赵丽  男  75.0   74.0    440301920503316932  440301920503316932
6   未知  男  91.0    0.0                   NaN                 NaN
7   张伟  男  75.0   95.0    965328710122691782  965328710122691782
8   陈静  男  94.0   81.0    440301930315103420  440301930315103420
9   吴刚  女  67.0   99.0  440301-850925-643020  440301850925643020

In [42]:
# （5）计算男、女语文数据平均成绩
df.groupby(by = '性别').agg({'语文成绩':'mean','数学成绩':'mean'})

      语文成绩    数学成绩
性别
女   81.000  99.500
男   72.875  72.375